# render.yaml

# Use the official 'v1' tag for the YAML specification
version: v1 

services:
  # ----------------------------------------------------------------
  # 1. Django Backend (Web Service)
  # ----------------------------------------------------------------
  - type: web
    name: hr-recruitment-backend
    env: python
    region: frankfurt

    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/manage.py collectstatic --noinput && python backend/manage.py migrate && gunicorn hr_core.wsgi:application"

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      
      - key: DATABASE_URL
        value: "YOUR_DATABASE_URL" # Use the Render dashboard to link securely
      - key: HF_SPACE_API_URL
        value: "YOUR_GRADIO_SPACE_API_URL"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://hr-recruitment-frontend.onrender.com"

  # ----------------------------------------------------------------
  # 2. React Frontend (Legacy Static Site Workaround)
  # ----------------------------------------------------------------
  - type: web  # Required to bypass your Render account's parsing issue
    name: hr-recruitment-frontend
    region: frankfurt
    runtime: static # ✅ CORRECT: Signals this web service should be treated as a static site
    
    rootDir: frontend
    
    buildCommand: "npm install && npm run build"
    publishPath: build # ✅ CORRECT: Use the modern 'publishPath' property
    
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://hr-recruitment-backend.onrender.com"