# render.yaml
version: "v1"

services:
  # ----------------------------------------------------------------
  # 1. Django Backend (Web Service - API)
  # ----------------------------------------------------------------
  - type: web
    name: hr-recruitment-backend
    env: python
    region: frankfurt
    plan: starter
    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt
      python -m spacy link en_core_web_md en_core_web_md --force

    startCommand: >
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn hr_core.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"

      # Link to PostgreSQL database service
      - key: DATABASE_URL
        fromDatabase:
          name: hr-recruitment-db
          property: connectionString

      # External Hugging Face API
      - key: HF_SPACE_API_URL
        value: "YOUR_GRADIO_SPACE_API_URL"

      # Email (Brevo SMTP)
      - key: BREVO_SMTP_KEY
        generateValue: true
      - key: BREVO_SMTP_LOGIN
        value: "your-brevo-login-email@example.com"

      # Celery Redis broker
      - key: CELERY_BROKER_URL
        value: "redis://hr-recruitment-redis:6379/0"

      - key: CORS_ALLOWED_ORIGINS
        value: "https://hr-recruitment-frontend.onrender.com"

  # ----------------------------------------------------------------
  # 2. Celery Worker (Background Service)
  # ----------------------------------------------------------------
  - type: worker
    name: hr-recruitment-worker
    env: python
    region: frankfurt
    plan: starter
    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt
      python -m spacy link en_core_web_md en_core_web_md --force

    startCommand: "celery -A hr_core worker -l info"

    envVars:
      - key: SECRET_KEY
        fromService:
          name: hr-recruitment-backend
          type: envVar
          property: SECRET_KEY
      - key: DATABASE_URL
        fromService:
          name: hr-recruitment-backend
          type: envVar
          property: DATABASE_URL
      - key: CELERY_BROKER_URL
        value: "redis://hr-recruitment-redis:6379/0"

  # ----------------------------------------------------------------
  # 3. Redis (Celery Message Broker)
  # ----------------------------------------------------------------
  - type: redis
    name: hr-recruitment-redis
    region: frankfurt
    plan: starter

  # ----------------------------------------------------------------
  # 4. PostgreSQL Database
  # ----------------------------------------------------------------
  - type: postgresql
    name: hr-recruitment-db
    region: frankfurt
    plan: starter

  # ----------------------------------------------------------------
  # 5. React Frontend (Static Site)
  # ----------------------------------------------------------------
  - type: web
    name: hr-recruitment-frontend
    region: frankfurt
    runtime: static
    rootDir: frontend

    buildCommand: "npm install && npm run build"
    publishPath: build

    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://hr-recruitment-backend.onrender.com"
