# render.yaml
version: v1

services:
  # ----------------------------------------------------------------
  # 1. Django Backend (Web Service)
  # ----------------------------------------------------------------
  - type: web
    name: hr-recruitment-backend
    env: python
    region: frankfurt

    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/manage.py collectstatic --noinput && python backend/manage.py migrate && gunicorn hr_core.wsgi:application"

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DATABASE_URL
      - key: HF_SPACE_API_URL
        value: "YOUR_GRADIO_SPACE_API_URL"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://hr-recruitment-frontend.onrender.com"

# ----------------------------------------------------------------
# 2. React Frontend (Static Site)
# ----------------------------------------------------------------
staticSites:
  - name: hr-recruitment-frontend
    region: frankfurt
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: build

    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://hr-recruitment-backend.onrender.com"
