version: 1

services:
  # ----------------------------------------------------------------
  # 1. Django Backend (Web API)
  # ----------------------------------------------------------------
  - type: web
    name: hr-recruitment-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy link en_core_web_md en_core_web_md --force
    startCommand: >
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn hr_core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DATABASE_URL
        fromDatabase:
          name: hr-recruitment-db
          property: connectionString
      - key: HF_SPACE_API_URL
        value: "YOUR_GRADIO_SPACE_API_URL"
      - key: BREVO_SMTP_KEY
        generateValue: true
      - key: BREVO_SMTP_LOGIN
        value: "your-brevo-login-email@example.com"
      - key: CELERY_BROKER_URL
        value: "redis://hr-recruitment-redis:6379/0"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://hr-recruitment-frontend.onrender.com"

  # ----------------------------------------------------------------
  # 2. Celery Worker
  # ----------------------------------------------------------------
  - type: worker
    name: hr-recruitment-worker
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy link en_core_web_md en_core_web_md --force
    startCommand: "celery -A hr_core worker -l info"
    envVars:
      - key: SECRET_KEY
        value: "<SAME_SECRET_KEY_AS_BACKEND>"
      - key: DATABASE_URL
        fromDatabase:
          name: hr-recruitment-db
          property: connectionString
      - key: CELERY_BROKER_URL
        value: "redis://hr-recruitment-redis:6379/0"

  # ----------------------------------------------------------------
  # 3. Redis Service
  # ----------------------------------------------------------------
  - type: redis
    name: hr-recruitment-redis
    region: frankfurt
    plan: free
    ipAllowList: [] # ✅ required by Render to allow internal access

  # ----------------------------------------------------------------
  # 4. React Frontend (Static Site)
  # ----------------------------------------------------------------
  - type: web
    name: hr-recruitment-frontend
    env: static
    plan: free
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend"
    staticPublishPath: frontend/build # ✅ correct field name
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://hr-recruitment-backend.onrender.com"

databases:
  - name: hr-recruitment-db
    region: frankfurt
