# render.yaml
# ==========================================================
# Render Deployment — Django Backend Only (Free Tier)
# ==========================================================

services:
  # --------------------------------------------------------
  # Django Backend (API)
  # --------------------------------------------------------
  - type: web
    name: hr-recruitment-backend
    env: python
    plan: free
    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_md
      python -m spacy link en_core_web_md en_core_web_md --force

    startCommand: |
      python manage.py collectstatic --noinput && \
      python manage.py migrate && \
      gunicorn hr_core.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DATABASE_URL
        value: "YOUR_EXTERNAL_DATABASE_URL"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com"
