# render.yaml

# REQUIRED: Must be 'v1' to support the 'static' type correctly.
version: v1 

services:
  # ----------------------------------------------------------------
  # 1. Django Backend (Web Service)
  # ----------------------------------------------------------------
  - type: web
    name: hr-recruitment-backend
    env: python
    region: frankfurt

    buildCommand: "pip install -r requirements.txt"
    # Note: startCommand should be on a single line
    startCommand: "python backend/manage.py collectstatic --noinput && python backend/manage.py migrate && gunicorn hr_core.wsgi:application"

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      
      # Use the Render linking feature for the database.
      - key: DATABASE_URL
        value: "YOUR_DATABASE_URL"  # PLACEHOLDER: Set this via linking in the dashboard
      - key: HF_SPACE_API_URL
        value: "YOUR_GRADIO_SPACE_API_URL" # PLACEHOLDER
      - key: CORS_ALLOWED_ORIGINS
        value: "https://hr-recruitment-frontend.onrender.com"

  # ----------------------------------------------------------------
  # 2. React Frontend (Static Site)
  # - CORRECTLY defined as 'static' for CDN delivery and low cost.
  # ----------------------------------------------------------------
  - type: static
    name: hr-recruitment-frontend
    region: frankfurt # Added region for consistency, though optional for Static
    
    # The root directory for the React code
    rootDir: frontend 
    
    # Installation and build steps for the React app
    buildCommand: "npm install && npm run build"
    
    # CORRECT field name for the output directory
    publishPath: build 

    envVars:
      # ONLY the backend URL is needed for the frontend
      - key: REACT_APP_BACKEND_URL
        value: "https://hr-recruitment-backend.onrender.com"