"""
Django settings for ABCD Bank HR Recruitment Agent.
Generated by Django 4.2.7.
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-abcd-bank-hr-agent-cpu-optimized')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']  # For Hugging Face Spaces

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'recruitment',
    'corsheaders',  # For React frontend
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hr_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hr_core.wsgi.application'
# use this for local development
# Database (SQLite for HF Spaces demo)
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
 #   }
#}
DATABASES = {
    'default': dj_database_url.config(
        # Use the DATABASE_URL environment variable from Render
        default=config('DATABASE_URL') 
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# CORS Settings (for React frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React default
    "http://127.0.0.1:3000",
]

# Email Configuration (SendGrid)
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY')
#EMAIL_HOST = 'smtp.sendgrid.net'
#EMAIL_HOST_USER = 'apikey'
#EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#DEFAULT_FROM_EMAIL = 'recruitment@abcd.com'

# --- Email Configuration (Brevo/Sendinblue) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Use config() for secure environment variable retrieval
BREVO_API_KEY = config('BREVO_API_KEY', default='')

# Brevo's SMTP Host and Port
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Brevo SMTP authentication (The host user is your Brevo login email)
EMAIL_HOST_USER = config('BREVO_SMTP_LOGIN', default='') # Your Brevo account email
EMAIL_HOST_PASSWORD = config('BREVO_SMTP_KEY', default=BREVO_API_KEY) # The specific SMTP Key from Brevo (or fallback to API key if you treat them as the same)

# Your desired sender address
DEFAULT_FROM_EMAIL = 'addtaye@gmail.com'  # Must be verified in Brevo
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Django-Q Configuration (disabled for CPU demo)
# Q_CLUSTER = {
#     'name': 'abcd_hr',
#     'workers': 1,
#     'timeout': 90,
#     'retry': 120,
#     'queue_limit': 500,
#     'bulk': 10,
#     'orm': 'default',
#     'sync': True,  # Critical for HF Spaces CPU
# }